export const types = {

    //Albasat Types
    GET_ALBASAT_TYPES: "GET_ALBASAT_TYPES",
    POST_ALBASAT_TYPE: "POST_ALBASAT_TYPE",
    PUT_ALBASAT_TYPE: "PUT_ALBASAT_TYPE",
    DELETE_ALBASAT_TYPE: "DELETE_ALBASAT_TYPE",

    //Cherk Types
    GET_CHERK_TYPES: "GET_CHERK_TYPES",
    POST_CHERK_TYPE: "POST_CHERK_TYPE",
    PUT_CHERK_TYPE: "PUT_CHERK_TYPE",
    DELETE_CHERK_TYPE: "DELETE_CHERK_TYPE",

    //Cherk Origin
    GET_CHERK_ORIGINS: "GET_CHERK_ORIGINS",
    POST_CHERK_ORIGIN: "POST_CHERK_ORIGIN",
    PUT_CHERK_ORIGIN: "PUT_CHERK_ORIGIN",
    DELETE_CHERK_ORIGIN: "DELETE_CHERK_ORIGIN",

    //Cherk Color 
    GET_CHERK_COLORS: "GET_CHERK_COLORS",
    POST_CHERK_COLOR: "POST_CHERK_COLOR",
    PUT_CHERK_COLOR: "PUT_CHERK_COLOR",
    DELETE_CHERK_COLOR: "DELETE_CHERK_COLOR",

    //Albasat Order
    GET_ALBASAT_ORDERS: "GET_ALBASAT_ORDERS",
    POST_ALBASAT_ORDER: "POST_ALBASAT_ORDER",
    PUT_ALBASAT_ORDER: "PUT_ALBASAT_ORDER",
    DELETE_ALBASAT_ORDER: "DELETE_ALBASAT_ORDER",

    //Customers
    GET_ALL_CUSTOMERS: "GET_ALL_CUSTOMERS",
    GET_CUSTOMERS: "GET_CUSTOMERS",
    POST_CUSTOMER: "POST_CUSTOMER",
    PUT_CUSTOMER: "PUT_CUSTOMER",
    DELETE_CUSTOMER: "DELETE_CUSTOMER",

    //Error
    ERROR: "ERROR"
}